"""empty message

Revision ID: 5c81ba241003
Revises: 
Create Date: 2024-02-19 15:06:39.446191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c81ba241003'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(255), nullable=False),
    sa.Column('content', sa.String(255), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    op.drop_table('ai_file_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_file_contents',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('req_original_file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('req_file_path', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('req_file_extenstion', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('req_body', mysql.TEXT(), nullable=True),
    sa.Column('res_original_file_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('res_file_path', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('res_file_extension', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('res_body', mysql.TEXT(), nullable=True),
    sa.Column('user_idx', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('prompt_idx', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('authority', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`authority` between 0 and 1)', name='users_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
